#!/usr/bin/env python
import os
import uuid
import argparse
import ROOT
import logging


log = logging.getLogger('scan-eos')
logging.basicConfig()
log.setLevel(logging.INFO)
# logging.


if __name__ == '__main__':
    
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--path', type=str, 
        default='/eos/atlas/user/q/qbuat', 
        help='default = %(default)s')
    args = parser.parse_args()

    ROOT.gROOT.Macro('$ROOTCOREDIR/scripts/load_packages.C')

    sniffer = ROOT.SH.SampleHandler()
    eos_list = ROOT.SH.DiskListEOS(args.path, 'root://eosatlas/' + args.path)
    ROOT.SH.ScanDir().scan(sniffer, eos_list) 
    log.info('\t --- Sample found on eos at {0} ---'.format(args.path))
    print ""
    for s in sniffer:
        log.info("\t {0}: {1} files".format(s.name(), s.numFiles()))
        log.info("")
    # sniffer.printContent()
